import {
  Bed,
  Bath,
  Maximize,
  Wifi,
  Shield,
  ParkingMeterIcon as Parking,
  Car,
  PocketIcon as Pool,
  Dumbbell,
  Trees,
  Sofa,
  Utensils,
  Gamepad,
  Coffee,
  Users,
  Briefcase,
  Truck,
  Headphones,
  Mail,
  Film,
  Wind,
  User,
  Sun,
  Box,
  Camera,
  Trash,
  Zap,
  Thermometer,
} from "lucide-react"

export const getIconByName = (name: string) => {
  const icons: Record<string, any> = {
    bed: Bed,
    bath: Bath,
    maximize: Maximize,
    wifi: Wifi,
    shield: Shield,
    parking: Parking,
    car: Car,
    pool: Pool,
    dumbbell: Dumbbell,
    trees: Trees,
    sofa: Sofa,
    utensils: Utensils,
    gamepad: Gamepad,
    coffee: Coffee,
    users: Users,
    briefcase: Briefcase,
    truck: Truck,
    headphones: Headphones,
    mail: Mail,
    film: Film,
    wind: Wind,
    user: User,
    sun: Sun,
    box: Box,
    camera: Camera,
    trash: Trash,
    zap: Zap,
    thermometer: Thermometer,
  }

  return icons[name] || Maximize
}

